# Problem 1 

In [94]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array = np.array([45,1,37,87,34])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
array.sort()
print(array)

[ 1 34 37 45 87]


# Problem 2

In [ ]:
#15 tekrar bak

In [104]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
_1 = np.array([10, 15, 30, 45, 60])
print(_1)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
_2 = np.arange(1,15,1)
print(_2)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
_3 = np.arange(50, 101, 5)
print(_3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
_4 = np.zeros(10)
print(_4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
_5 = np.ones(10)
print(_5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
_6 = np.linspace(0, 100, 5)
print(_6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
_7 = np.random.randint(10, 30, 5)
print(_7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
_8 = np.random.uniform(-1, 1, 10) #Generates numbers specificly between 1 and -1 and takes parameters*
print(_8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
_9 = np.random.normal(10, 50, (3, 5))
print(_9)

matris = _9

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
toplam_satir = np.sum(matris, axis=1)
print(toplam_satir)

toplam_sutun = np.sum(matris, axis=0)
print(toplam_sutun)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(matris.max())
print(matris.min())
print(matris.mean())

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(np.max(matris))

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
seri2 = np.arange(10, 21)
print(seri2[0:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(seri2[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(seri2[:0]) #bak

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(seri2[2:3])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(seri2[0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
def power(x):
    print(x**2)
power(seri2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.


[10 15 30 45 60]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[24 22 24 23 26]
[ 0.07472722 -0.62855963 -0.14607374 -0.14932127  0.08543694  0.88524488
 -0.3668199   0.96634905 -0.90807884  0.00192393]
[[ 54.5177482    5.43248436  58.49103792 -19.48991966  49.81010013]
 [-28.32300155 -16.51596183  38.83431246 -57.3956342  -11.35870021]
 [ 24.52513951  17.58165428  21.7770071   55.32523174 -47.97356113]]
[148.76145095 -74.75898533  71.2354715 ]
[ 50.71988616   6.49817682 119.10235748 -21.56032212  -9.52216121]
58.49103792375736
-57.39563419646399
9.682529141764071
58.49103792375736
[10 11 12]
[20 19 18 17 16 15 14 13 12 11 10]
[]
[12]
10
[100 121 144 169 196 225 256 289 324 361 400]
