# Problem 1 

In [5]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array = np.array([45,1,37,87,34])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
array.sort()
print(array)

[ 1 34 37 45 87]


# Problem 2

In [ ]:
#15 tekrar bak

In [6]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
_1 = np.array([10, 15, 30, 45, 60])
print(_1)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
_2 = np.arange(1,15,1)
print(_2)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
_3 = np.arange(50, 101, 5)
print(_3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
_4 = np.zeros(10)
print(_4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
_5 = np.ones(10)
print(_5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
_6 = np.linspace(0, 100, 5)
print(_6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
_7 = np.random.randint(10, 30, 5)
print(_7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
_8 = np.random.uniform(-1, 1, 10) #Generates numbers specificly between 1 and -1 and takes parameters*
print(_8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
_9 = np.random.normal(10, 50, (3, 5))
print(_9)

matris = _9

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
toplam_satir = np.sum(matris, axis=1)
print(toplam_satir)

toplam_sutun = np.sum(matris, axis=0)
print(toplam_sutun)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(matris.max())
print(matris.min())
print(matris.mean())

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(np.max(matris))

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
seri2 = np.arange(10, 21)
print(seri2[0:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(seri2[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(seri2[:0]) #bak

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(seri2[2:3])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(seri2[0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
def power(x):
    print(x**2)
power(seri2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
_19 = np.random.randint(-50, 51, size=(3, 5))
__19 = _19[(_19 > 0) & (_19 % 2 == 0)]

[10 15 30 45 60]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[15 26 14 18 27]
[-0.45048289  0.9958681  -0.57133309 -0.01399703  0.53500253  0.66531262
 -0.05152229 -0.65960211  0.25200878 -0.38493424]
[[ 26.83274868   2.02640018 -39.04737635  24.70211566  80.24365401]
 [-76.09520142  31.04408183  43.04311482  37.5182422   58.05672898]
 [ 58.32217997  60.08869464  84.98097259 -49.23040621   9.46666876]]
[ 94.75754218  93.5669664  163.62810975]
[  9.05972723  93.15917664  88.97671106  12.98995166 147.76705175]
84.9809725852608
-76.09520142136023
23.46350788883047
84.9809725852608
[10 11 12]
[20 19 18 17 16 15 14 13 12 11 10]
[]
[12]
10
[100 121 144 169 196 225 256 289 324 361 400]
