# Problem 1

In [112]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris = np.random.randint(0, 10, 5)
print(matris)

# 3 - matris'in boyutunu öğrenin
print(matris.shape)

# 4 - matris'i yeniden boyutlandırın
print(matris.reshape(5,1))

# 5 - matris'in boyut sayısını öğrenin
print(matris.ndim)

[7 4 4 8 7]
(5,)
[[7]
 [4]
 [4]
 [8]
 [7]]
1


# Problem 2

In [92]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
seri = np.array(range(1, 11, 2)) 
print(seri)

# 2 - Oluşturduğunuz matrisi parçalayın
_seri = seri.reshape(5,1)
print(_seri)

# 3 - Parçalanmış matrisleri birleştirin
np.concatenate(_seri)   

[1 3 5 7 9]
[[1]
 [3]
 [5]
 [7]
 [9]]


array([1, 3, 5, 7, 9])

# Problem 3

In [78]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
a = np.random.normal(5, 100, 20)
print(f"{a}/\n")
print(f"{a[0::2]}\n")

# 2 - matris'in özelliklerini inceleyin
print(a.size) #size: Toplam Eleman Sayisi
print(a.shape) #shape: Boyut Bilgisi
print(a.ndim)  #ndim: Boyut Sayisi
print(a.dtype) #dtype: Veri Tipi

[ -54.97869166  -23.00949637  -29.45614319 -158.60288295 -110.19861818
 -155.54523903  -99.59774268  -71.09732911  -75.00039855  -34.87667879
  160.11311785  -53.31045066  -42.30210368   16.89910077   59.0202252
   65.31661384   72.66419002  153.47163013  -48.63540555   68.21264054]/

[ -54.97869166  -29.45614319 -110.19861818  -99.59774268  -75.00039855
  160.11311785  -42.30210368   59.0202252    72.66419002  -48.63540555]

20
(20,)
1
float64
